export type Pos = 'n' | 'v' | 'adj' | 'adv'

export interface FamilyMember {
  word: string
  pos: Pos
}

export interface Family {
  members: FamilyMember[]
}

export const POS_LABELS: Record<Pos, string> = {
  n: '名词',
  v: '动词',
  adj: '形容词',
  adv: '副词',
}

const FAMILIES: Family[] = [
  { members: [{ word: 'abandon', pos: 'v' }, { word: 'abandonment', pos: 'n' }, { word: 'abandoned', pos: 'adj' }] },
  { members: [{ word: 'absent', pos: 'adj' }, { word: 'absence', pos: 'n' }] },
  { members: [{ word: 'accept', pos: 'v' }, { word: 'acceptance', pos: 'n' }, { word: 'acceptable', pos: 'adj' }] },
  { members: [{ word: 'access', pos: 'n' }, { word: 'accessible', pos: 'adj' }, { word: 'accessibility', pos: 'n' }] },
  { members: [{ word: 'accommodate', pos: 'v' }, { word: 'accommodation', pos: 'n' }] },
  { members: [{ word: 'accomplish', pos: 'v' }, { word: 'accomplishment', pos: 'n' }] },
  { members: [{ word: 'account', pos: 'n' }, { word: 'accountable', pos: 'adj' }, { word: 'accountability', pos: 'n' }] },
  { members: [{ word: 'accurate', pos: 'adj' }, { word: 'accuracy', pos: 'n' }, { word: 'accurately', pos: 'adv' }] },
  { members: [{ word: 'achieve', pos: 'v' }, { word: 'achievement', pos: 'n' }] },
  { members: [{ word: 'adapt', pos: 'v' }, { word: 'adaptation', pos: 'n' }, { word: 'adaptable', pos: 'adj' }] },
  { members: [{ word: 'adequate', pos: 'adj' }, { word: 'adequacy', pos: 'n' }, { word: 'adequately', pos: 'adv' }] },
  { members: [{ word: 'adjust', pos: 'v' }, { word: 'adjustment', pos: 'n' }, { word: 'adjustable', pos: 'adj' }] },
  { members: [{ word: 'administer', pos: 'v' }, { word: 'administration', pos: 'n' }, { word: 'administrative', pos: 'adj' }] },
  { members: [{ word: 'admit', pos: 'v' }, { word: 'admission', pos: 'n' }] },
  { members: [{ word: 'adopt', pos: 'v' }, { word: 'adoption', pos: 'n' }] },
  { members: [{ word: 'advance', pos: 'v' }, { word: 'advancement', pos: 'n' }, { word: 'advanced', pos: 'adj' }] },
  { members: [{ word: 'agree', pos: 'v' }, { word: 'agreement', pos: 'n' }, { word: 'agreeable', pos: 'adj' }] },
  { members: [{ word: 'amaze', pos: 'v' }, { word: 'amazement', pos: 'n' }, { word: 'amazing', pos: 'adj' }] },
  { members: [{ word: 'analyze', pos: 'v' }, { word: 'analysis', pos: 'n' }, { word: 'analytical', pos: 'adj' }] },
  { members: [{ word: 'announce', pos: 'v' }, { word: 'announcement', pos: 'n' }] },
  { members: [{ word: 'annoy', pos: 'v' }, { word: 'annoyance', pos: 'n' }, { word: 'annoying', pos: 'adj' }] },
  { members: [{ word: 'anticipate', pos: 'v' }, { word: 'anticipation', pos: 'n' }] },
  { members: [{ word: 'apply', pos: 'v' }, { word: 'application', pos: 'n' }, { word: 'applicant', pos: 'n' }] },
  { members: [{ word: 'appoint', pos: 'v' }, { word: 'appointment', pos: 'n' }] },
  { members: [{ word: 'appreciate', pos: 'v' }, { word: 'appreciation', pos: 'n' }, { word: 'appreciative', pos: 'adj' }] },
  { members: [{ word: 'approach', pos: 'v' }, { word: 'approachable', pos: 'adj' }] },
  { members: [{ word: 'approve', pos: 'v' }, { word: 'approval', pos: 'n' }] },
  { members: [{ word: 'argue', pos: 'v' }, { word: 'argument', pos: 'n' }] },
  { members: [{ word: 'arrange', pos: 'v' }, { word: 'arrangement', pos: 'n' }] },
  { members: [{ word: 'arrive', pos: 'v' }, { word: 'arrival', pos: 'n' }] },
  { members: [{ word: 'assess', pos: 'v' }, { word: 'assessment', pos: 'n' }] },
  { members: [{ word: 'assist', pos: 'v' }, { word: 'assistance', pos: 'n' }, { word: 'assistant', pos: 'n' }] },
  { members: [{ word: 'assume', pos: 'v' }, { word: 'assumption', pos: 'n' }] },
  { members: [{ word: 'assure', pos: 'v' }, { word: 'assurance', pos: 'n' }] },
  { members: [{ word: 'attract', pos: 'v' }, { word: 'attraction', pos: 'n' }, { word: 'attractive', pos: 'adj' }] },
  { members: [{ word: 'authorize', pos: 'v' }, { word: 'authority', pos: 'n' }] },
  { members: [{ word: 'available', pos: 'adj' }, { word: 'availability', pos: 'n' }] },
  { members: [{ word: 'avoid', pos: 'v' }, { word: 'avoidance', pos: 'n' }] },
  { members: [{ word: 'aware', pos: 'adj' }, { word: 'awareness', pos: 'n' }] },
  { members: [{ word: 'behave', pos: 'v' }, { word: 'behavior', pos: 'n' }] },
  { members: [{ word: 'believe', pos: 'v' }, { word: 'belief', pos: 'n' }] },
  { members: [{ word: 'benefit', pos: 'n' }, { word: 'beneficial', pos: 'adj' }] },
  { members: [{ word: 'bore', pos: 'v' }, { word: 'boredom', pos: 'n' }, { word: 'boring', pos: 'adj' }] },
  { members: [{ word: 'calculate', pos: 'v' }, { word: 'calculation', pos: 'n' }, { word: 'calculator', pos: 'n' }] },
  { members: [{ word: 'capable', pos: 'adj' }, { word: 'capability', pos: 'n' }, { word: 'capacity', pos: 'n' }] },
  { members: [{ word: 'care', pos: 'v' }, { word: 'careful', pos: 'adj' }, { word: 'carefully', pos: 'adv' }] },
  { members: [{ word: 'celebrate', pos: 'v' }, { word: 'celebration', pos: 'n' }] },
  { members: [{ word: 'certain', pos: 'adj' }, { word: 'certainty', pos: 'n' }, { word: 'certainly', pos: 'adv' }] },
  { members: [{ word: 'challenge', pos: 'n' }, { word: 'challenging', pos: 'adj' }] },
  { members: [{ word: 'choose', pos: 'v' }, { word: 'choice', pos: 'n' }] },
  { members: [{ word: 'classify', pos: 'v' }, { word: 'classification', pos: 'n' }] },
  { members: [{ word: 'collect', pos: 'v' }, { word: 'collection', pos: 'n' }, { word: 'collector', pos: 'n' }] },
  { members: [{ word: 'comfort', pos: 'n' }, { word: 'comfortable', pos: 'adj' }] },
  { members: [{ word: 'commit', pos: 'v' }, { word: 'commitment', pos: 'n' }] },
  { members: [{ word: 'communicate', pos: 'v' }, { word: 'communication', pos: 'n' }] },
  { members: [{ word: 'compare', pos: 'v' }, { word: 'comparison', pos: 'n' }] },
  { members: [{ word: 'compete', pos: 'v' }, { word: 'competition', pos: 'n' }, { word: 'competitive', pos: 'adj' }] },
  { members: [{ word: 'complain', pos: 'v' }, { word: 'complaint', pos: 'n' }] },
  { members: [{ word: 'complete', pos: 'v' }, { word: 'completion', pos: 'n' }] },
  { members: [{ word: 'compose', pos: 'v' }, { word: 'composition', pos: 'n' }] },
  { members: [{ word: 'conclude', pos: 'v' }, { word: 'conclusion', pos: 'n' }] },
  { members: [{ word: 'confidence', pos: 'n' }, { word: 'confident', pos: 'adj' }, { word: 'confidently', pos: 'adv' }] },
  { members: [{ word: 'confuse', pos: 'v' }, { word: 'confusion', pos: 'n' }, { word: 'confusing', pos: 'adj' }] },
  { members: [{ word: 'connect', pos: 'v' }, { word: 'connection', pos: 'n' }] },
  { members: [{ word: 'consider', pos: 'v' }, { word: 'consideration', pos: 'n' }, { word: 'considerate', pos: 'adj' }] },
  { members: [{ word: 'consist', pos: 'v' }, { word: 'consistent', pos: 'adj' }, { word: 'consistency', pos: 'n' }] },
  { members: [{ word: 'constitute', pos: 'v' }, { word: 'constitution', pos: 'n' }] },
  { members: [{ word: 'construct', pos: 'v' }, { word: 'construction', pos: 'n' }] },
  { members: [{ word: 'consume', pos: 'v' }, { word: 'consumption', pos: 'n' }] },
  { members: [{ word: 'contribute', pos: 'v' }, { word: 'contribution', pos: 'n' }] },
  { members: [{ word: 'convert', pos: 'v' }, { word: 'conversion', pos: 'n' }] },
  { members: [{ word: 'convince', pos: 'v' }, { word: 'conviction', pos: 'n' }] },
  { members: [{ word: 'correct', pos: 'adj' }, { word: 'correction', pos: 'n' }] },
  { members: [{ word: 'create', pos: 'v' }, { word: 'creation', pos: 'n' }, { word: 'creative', pos: 'adj' }] },
  { members: [{ word: 'criticize', pos: 'v' }, { word: 'criticism', pos: 'n' }, { word: 'critic', pos: 'n' }] },
  { members: [{ word: 'curious', pos: 'adj' }, { word: 'curiosity', pos: 'n' }] },
  { members: [{ word: 'decide', pos: 'v' }, { word: 'decision', pos: 'n' }] },
  { members: [{ word: 'declare', pos: 'v' }, { word: 'declaration', pos: 'n' }] },
  { members: [{ word: 'dedicate', pos: 'v' }, { word: 'dedication', pos: 'n' }] },
  { members: [{ word: 'define', pos: 'v' }, { word: 'definition', pos: 'n' }] },
  { members: [{ word: 'deliver', pos: 'v' }, { word: 'delivery', pos: 'n' }] },
  { members: [{ word: 'depend', pos: 'v' }, { word: 'dependence', pos: 'n' }, { word: 'dependent', pos: 'adj' }] },
  { members: [{ word: 'describe', pos: 'v' }, { word: 'description', pos: 'n' }] },
  { members: [{ word: 'destroy', pos: 'v' }, { word: 'destruction', pos: 'n' }, { word: 'destructive', pos: 'adj' }] },
  { members: [{ word: 'determine', pos: 'v' }, { word: 'determination', pos: 'n' }] },
  { members: [{ word: 'develop', pos: 'v' }, { word: 'development', pos: 'n' }] },
  { members: [{ word: 'differ', pos: 'v' }, { word: 'difference', pos: 'n' }, { word: 'different', pos: 'adj' }] },
  { members: [{ word: 'direct', pos: 'adj' }, { word: 'direction', pos: 'n' }, { word: 'director', pos: 'n' }] },
  { members: [{ word: 'disappear', pos: 'v' }, { word: 'disappearance', pos: 'n' }] },
  { members: [{ word: 'disappoint', pos: 'v' }, { word: 'disappointment', pos: 'n' }, { word: 'disappointing', pos: 'adj' }] },
  { members: [{ word: 'discover', pos: 'v' }, { word: 'discovery', pos: 'n' }] },
  { members: [{ word: 'discuss', pos: 'v' }, { word: 'discussion', pos: 'n' }] },
  { members: [{ word: 'distribute', pos: 'v' }, { word: 'distribution', pos: 'n' }] },
  { members: [{ word: 'divide', pos: 'v' }, { word: 'division', pos: 'n' }] },
  { members: [{ word: 'dominate', pos: 'v' }, { word: 'domination', pos: 'n' }, { word: 'dominant', pos: 'adj' }] },
  { members: [{ word: 'economy', pos: 'n' }, { word: 'economic', pos: 'adj' }, { word: 'economist', pos: 'n' }] },
  { members: [{ word: 'educate', pos: 'v' }, { word: 'education', pos: 'n' }] },
  { members: [{ word: 'effect', pos: 'n' }, { word: 'effective', pos: 'adj' }, { word: 'effectively', pos: 'adv' }] },
  { members: [{ word: 'efficient', pos: 'adj' }, { word: 'efficiency', pos: 'n' }, { word: 'efficiently', pos: 'adv' }] },
  { members: [{ word: 'emerge', pos: 'v' }, { word: 'emergence', pos: 'n' }, { word: 'emergency', pos: 'n' }] },
  { members: [{ word: 'employ', pos: 'v' }, { word: 'employment', pos: 'n' }, { word: 'employee', pos: 'n' }] },
  { members: [{ word: 'encourage', pos: 'v' }, { word: 'encouragement', pos: 'n' }] },
  { members: [{ word: 'enter', pos: 'v' }, { word: 'entrance', pos: 'n' }, { word: 'entry', pos: 'n' }] },
  { members: [{ word: 'entertain', pos: 'v' }, { word: 'entertainment', pos: 'n' }] },
  { members: [{ word: 'enthusiasm', pos: 'n' }, { word: 'enthusiastic', pos: 'adj' }] },
  { members: [{ word: 'environment', pos: 'n' }, { word: 'environmental', pos: 'adj' }] },
  { members: [{ word: 'equal', pos: 'adj' }, { word: 'equality', pos: 'n' }] },
  { members: [{ word: 'equip', pos: 'v' }, { word: 'equipment', pos: 'n' }] },
  { members: [{ word: 'essential', pos: 'adj' }, { word: 'essence', pos: 'n' }] },
  { members: [{ word: 'establish', pos: 'v' }, { word: 'establishment', pos: 'n' }] },
  { members: [{ word: 'evaluate', pos: 'v' }, { word: 'evaluation', pos: 'n' }] },
  { members: [{ word: 'evident', pos: 'adj' }, { word: 'evidence', pos: 'n' }] },
  { members: [{ word: 'evolve', pos: 'v' }, { word: 'evolution', pos: 'n' }] },
  { members: [{ word: 'examine', pos: 'v' }, { word: 'examination', pos: 'n' }] },
  { members: [{ word: 'exceed', pos: 'v' }, { word: 'excess', pos: 'n' }, { word: 'excessive', pos: 'adj' }] },
  { members: [{ word: 'except', pos: 'prep' as Pos }, { word: 'exception', pos: 'n' }, { word: 'exceptional', pos: 'adj' }] },
  { members: [{ word: 'exist', pos: 'v' }, { word: 'existence', pos: 'n' }] },
  { members: [{ word: 'expand', pos: 'v' }, { word: 'expansion', pos: 'n' }] },
  { members: [{ word: 'expect', pos: 'v' }, { word: 'expectation', pos: 'n' }] },
  { members: [{ word: 'explain', pos: 'v' }, { word: 'explanation', pos: 'n' }] },
  { members: [{ word: 'explode', pos: 'v' }, { word: 'explosion', pos: 'n' }] },
  { members: [{ word: 'explore', pos: 'v' }, { word: 'exploration', pos: 'n' }] },
  { members: [{ word: 'expose', pos: 'v' }, { word: 'exposure', pos: 'n' }] },
  { members: [{ word: 'express', pos: 'v' }, { word: 'expression', pos: 'n' }, { word: 'expressive', pos: 'adj' }] },
  { members: [{ word: 'extend', pos: 'v' }, { word: 'extension', pos: 'n' }, { word: 'extensive', pos: 'adj' }] },
  { members: [{ word: 'fail', pos: 'v' }, { word: 'failure', pos: 'n' }] },
  { members: [{ word: 'fair', pos: 'adj' }, { word: 'fairness', pos: 'n' }] },
  { members: [{ word: 'familiar', pos: 'adj' }, { word: 'familiarity', pos: 'n' }, { word: 'familiarize', pos: 'v' }] },
  { members: [{ word: 'favor', pos: 'n' }, { word: 'favorable', pos: 'adj' }] },
  { members: [{ word: 'flexible', pos: 'adj' }, { word: 'flexibility', pos: 'n' }] },
  { members: [{ word: 'focus', pos: 'v' }, { word: 'focused', pos: 'adj' }] },
  { members: [{ word: 'foresee', pos: 'v' }, { word: 'foreseeable', pos: 'adj' }] },
  { members: [{ word: 'formal', pos: 'adj' }, { word: 'formality', pos: 'n' }] },
  { members: [{ word: 'fortune', pos: 'n' }, { word: 'fortunate', pos: 'adj' }, { word: 'fortunately', pos: 'adv' }] },
  { members: [{ word: 'frequent', pos: 'adj' }, { word: 'frequency', pos: 'n' }, { word: 'frequently', pos: 'adv' }] },
  { members: [{ word: 'glory', pos: 'n' }, { word: 'glorify', pos: 'v' }, { word: 'glorious', pos: 'adj' }] },
  { members: [{ word: 'grow', pos: 'v' }, { word: 'growth', pos: 'n' }] },
  { members: [{ word: 'happy', pos: 'adj' }, { word: 'happiness', pos: 'n' }, { word: 'happily', pos: 'adv' }] },
  { members: [{ word: 'harm', pos: 'n' }, { word: 'harmful', pos: 'adj' }] },
  { members: [{ word: 'hesitate', pos: 'v' }, { word: 'hesitation', pos: 'n' }] },
  { members: [{ word: 'high', pos: 'adj' }, { word: 'height', pos: 'n' }, { word: 'highly', pos: 'adv' }] },
  { members: [{ word: 'honest', pos: 'adj' }, { word: 'honesty', pos: 'n' }] },
  { members: [{ word: 'hope', pos: 'v' }, { word: 'hopeful', pos: 'adj' }] },
  { members: [{ word: 'identify', pos: 'v' }, { word: 'identification', pos: 'n' }] },
  { members: [{ word: 'ignore', pos: 'v' }, { word: 'ignorance', pos: 'n' }, { word: 'ignorant', pos: 'adj' }] },
  { members: [{ word: 'imagine', pos: 'v' }, { word: 'imagination', pos: 'n' }, { word: 'imaginative', pos: 'adj' }] },
  { members: [{ word: 'imitate', pos: 'v' }, { word: 'imitation', pos: 'n' }] },
  { members: [{ word: 'immigrate', pos: 'v' }, { word: 'immigration', pos: 'n' }, { word: 'immigrant', pos: 'n' }] },
  { members: [{ word: 'impact', pos: 'n' }, { word: 'impactive', pos: 'adj' }] },
  { members: [{ word: 'imply', pos: 'v' }, { word: 'implication', pos: 'n' }] },
  { members: [{ word: 'import', pos: 'v' }, { word: 'importance', pos: 'n' }, { word: 'important', pos: 'adj' }] },
  { members: [{ word: 'impress', pos: 'v' }, { word: 'impression', pos: 'n' }, { word: 'impressive', pos: 'adj' }] },
  { members: [{ word: 'improve', pos: 'v' }, { word: 'improvement', pos: 'n' }] },
  { members: [{ word: 'include', pos: 'v' }, { word: 'inclusion', pos: 'n' }] },
  { members: [{ word: 'increase', pos: 'v' }, { word: 'increasingly', pos: 'adv' }] },
  { members: [{ word: 'independent', pos: 'adj' }, { word: 'independence', pos: 'n' }] },
  { members: [{ word: 'indicate', pos: 'v' }, { word: 'indication', pos: 'n' }] },
  { members: [{ word: 'influence', pos: 'n' }, { word: 'influential', pos: 'adj' }] },
  { members: [{ word: 'inform', pos: 'v' }, { word: 'information', pos: 'n' }] },
  { members: [{ word: 'injure', pos: 'v' }, { word: 'injury', pos: 'n' }] },
  { members: [{ word: 'innovate', pos: 'v' }, { word: 'innovation', pos: 'n' }, { word: 'innovative', pos: 'adj' }] },
  { members: [{ word: 'inspire', pos: 'v' }, { word: 'inspiration', pos: 'n' }] },
  { members: [{ word: 'instruct', pos: 'v' }, { word: 'instruction', pos: 'n' }, { word: 'instructor', pos: 'n' }] },
  { members: [{ word: 'insure', pos: 'v' }, { word: 'insurance', pos: 'n' }] },
  { members: [{ word: 'intelligent', pos: 'adj' }, { word: 'intelligence', pos: 'n' }] },
  { members: [{ word: 'intend', pos: 'v' }, { word: 'intention', pos: 'n' }] },
  { members: [{ word: 'interact', pos: 'v' }, { word: 'interaction', pos: 'n' }] },
  { members: [{ word: 'interpret', pos: 'v' }, { word: 'interpretation', pos: 'n' }, { word: 'interpreter', pos: 'n' }] },
  { members: [{ word: 'intervene', pos: 'v' }, { word: 'intervention', pos: 'n' }] },
  { members: [{ word: 'introduce', pos: 'v' }, { word: 'introduction', pos: 'n' }] },
  { members: [{ word: 'invent', pos: 'v' }, { word: 'invention', pos: 'n' }, { word: 'inventor', pos: 'n' }] },
  { members: [{ word: 'invest', pos: 'v' }, { word: 'investment', pos: 'n' }, { word: 'investor', pos: 'n' }] },
  { members: [{ word: 'investigate', pos: 'v' }, { word: 'investigation', pos: 'n' }] },
  { members: [{ word: 'invite', pos: 'v' }, { word: 'invitation', pos: 'n' }] },
  { members: [{ word: 'involve', pos: 'v' }, { word: 'involvement', pos: 'n' }] },
  { members: [{ word: 'judge', pos: 'v' }, { word: 'judgment', pos: 'n' }] },
  { members: [{ word: 'justify', pos: 'v' }, { word: 'justification', pos: 'n' }] },
  { members: [{ word: 'know', pos: 'v' }, { word: 'knowledge', pos: 'n' }] },
  { members: [{ word: 'legal', pos: 'adj' }, { word: 'legality', pos: 'n' }, { word: 'legally', pos: 'adv' }] },
  { members: [{ word: 'liberal', pos: 'adj' }, { word: 'liberty', pos: 'n' }] },
  { members: [{ word: 'limit', pos: 'v' }, { word: 'limitation', pos: 'n' }, { word: 'limited', pos: 'adj' }] },
  { members: [{ word: 'logical', pos: 'adj' }, { word: 'logic', pos: 'n' }, { word: 'logically', pos: 'adv' }] },
  { members: [{ word: 'maintain', pos: 'v' }, { word: 'maintenance', pos: 'n' }] },
  { members: [{ word: 'major', pos: 'adj' }, { word: 'majority', pos: 'n' }] },
  { members: [{ word: 'manage', pos: 'v' }, { word: 'management', pos: 'n' }, { word: 'manager', pos: 'n' }] },
  { members: [{ word: 'mature', pos: 'adj' }, { word: 'maturity', pos: 'n' }] },
  { members: [{ word: 'mean', pos: 'v' }, { word: 'meaning', pos: 'n' }, { word: 'meaningful', pos: 'adj' }] },
  { members: [{ word: 'measure', pos: 'v' }, { word: 'measurement', pos: 'n' }] },
  { members: [{ word: 'medical', pos: 'adj' }, { word: 'medicine', pos: 'n' }] },
  { members: [{ word: 'memorize', pos: 'v' }, { word: 'memory', pos: 'n' }] },
  { members: [{ word: 'minor', pos: 'adj' }, { word: 'minority', pos: 'n' }] },
  { members: [{ word: 'mislead', pos: 'v' }, { word: 'misleading', pos: 'adj' }] },
  { members: [{ word: 'modern', pos: 'adj' }, { word: 'modernize', pos: 'v' }, { word: 'modernization', pos: 'n' }] },
  { members: [{ word: 'modify', pos: 'v' }, { word: 'modification', pos: 'n' }] },
  { members: [{ word: 'motivate', pos: 'v' }, { word: 'motivation', pos: 'n' }] },
  { members: [{ word: 'move', pos: 'v' }, { word: 'movement', pos: 'n' }] },
  { members: [{ word: 'mystery', pos: 'n' }, { word: 'mysterious', pos: 'adj' }] },
  { members: [{ word: 'necessary', pos: 'adj' }, { word: 'necessity', pos: 'n' }] },
  { members: [{ word: 'neglect', pos: 'v' }, { word: 'negligence', pos: 'n' }, { word: 'negligent', pos: 'adj' }] },
  { members: [{ word: 'normal', pos: 'adj' }, { word: 'normality', pos: 'n' }, { word: 'normally', pos: 'adv' }] },
  { members: [{ word: 'object', pos: 'v' }, { word: 'objection', pos: 'n' }, { word: 'objective', pos: 'adj' }] },
  { members: [{ word: 'observe', pos: 'v' }, { word: 'observation', pos: 'n' }, { word: 'observer', pos: 'n' }] },
  { members: [{ word: 'obvious', pos: 'adj' }, { word: 'obviously', pos: 'adv' }] },
  { members: [{ word: 'occupy', pos: 'v' }, { word: 'occupation', pos: 'n' }] },
  { members: [{ word: 'offend', pos: 'v' }, { word: 'offense', pos: 'n' }, { word: 'offensive', pos: 'adj' }] },
  { members: [{ word: 'operate', pos: 'v' }, { word: 'operation', pos: 'n' }, { word: 'operator', pos: 'n' }] },
  { members: [{ word: 'oppose', pos: 'v' }, { word: 'opposition', pos: 'n' }, { word: 'opposite', pos: 'adj' }] },
  { members: [{ word: 'organize', pos: 'v' }, { word: 'organization', pos: 'n' }] },
  { members: [{ word: 'originate', pos: 'v' }, { word: 'origin', pos: 'n' }, { word: 'original', pos: 'adj' }] },
  { members: [{ word: 'participate', pos: 'v' }, { word: 'participation', pos: 'n' }] },
  { members: [{ word: 'perform', pos: 'v' }, { word: 'performance', pos: 'n' }, { word: 'performer', pos: 'n' }] },
  { members: [{ word: 'permit', pos: 'v' }, { word: 'permission', pos: 'n' }] },
  { members: [{ word: 'persist', pos: 'v' }, { word: 'persistence', pos: 'n' }, { word: 'persistent', pos: 'adj' }] },
  { members: [{ word: 'persuade', pos: 'v' }, { word: 'persuasion', pos: 'n' }, { word: 'persuasive', pos: 'adj' }] },
  { members: [{ word: 'please', pos: 'v' }, { word: 'pleasure', pos: 'n' }, { word: 'pleasant', pos: 'adj' }] },
  { members: [{ word: 'poison', pos: 'n' }, { word: 'poisonous', pos: 'adj' }] },
  { members: [{ word: 'politics', pos: 'n' }, { word: 'political', pos: 'adj' }, { word: 'politician', pos: 'n' }] },
  { members: [{ word: 'popular', pos: 'adj' }, { word: 'popularity', pos: 'n' }] },
  { members: [{ word: 'possess', pos: 'v' }, { word: 'possession', pos: 'n' }] },
  { members: [{ word: 'possible', pos: 'adj' }, { word: 'possibility', pos: 'n' }, { word: 'possibly', pos: 'adv' }] },
  { members: [{ word: 'predict', pos: 'v' }, { word: 'prediction', pos: 'n' }] },
  { members: [{ word: 'prefer', pos: 'v' }, { word: 'preference', pos: 'n' }] },
  { members: [{ word: 'prepare', pos: 'v' }, { word: 'preparation', pos: 'n' }] },
  { members: [{ word: 'present', pos: 'v' }, { word: 'presence', pos: 'n' }, { word: 'presentation', pos: 'n' }] },
  { members: [{ word: 'preserve', pos: 'v' }, { word: 'preservation', pos: 'n' }] },
  { members: [{ word: 'press', pos: 'v' }, { word: 'pressure', pos: 'n' }] },
  { members: [{ word: 'produce', pos: 'v' }, { word: 'production', pos: 'n' }, { word: 'product', pos: 'n' }] },
  { members: [{ word: 'profess', pos: 'v' }, { word: 'profession', pos: 'n' }, { word: 'professional', pos: 'adj' }] },
  { members: [{ word: 'promote', pos: 'v' }, { word: 'promotion', pos: 'n' }] },
  { members: [{ word: 'propose', pos: 'v' }, { word: 'proposal', pos: 'n' }] },
  { members: [{ word: 'protect', pos: 'v' }, { word: 'protection', pos: 'n' }, { word: 'protective', pos: 'adj' }] },
  { members: [{ word: 'prove', pos: 'v' }, { word: 'proof', pos: 'n' }] },
  { members: [{ word: 'provide', pos: 'v' }, { word: 'provision', pos: 'n' }] },
  { members: [{ word: 'publish', pos: 'v' }, { word: 'publication', pos: 'n' }] },
  { members: [{ word: 'punish', pos: 'v' }, { word: 'punishment', pos: 'n' }] },
  { members: [{ word: 'qualify', pos: 'v' }, { word: 'qualification', pos: 'n' }] },
  { members: [{ word: 'quantity', pos: 'n' }, { word: 'quantify', pos: 'v' }] },
  { members: [{ word: 'react', pos: 'v' }, { word: 'reaction', pos: 'n' }] },
  { members: [{ word: 'real', pos: 'adj' }, { word: 'reality', pos: 'n' }, { word: 'really', pos: 'adv' }] },
  { members: [{ word: 'reason', pos: 'n' }, { word: 'reasonable', pos: 'adj' }] },
  { members: [{ word: 'recognize', pos: 'v' }, { word: 'recognition', pos: 'n' }] },
  { members: [{ word: 'recommend', pos: 'v' }, { word: 'recommendation', pos: 'n' }] },
  { members: [{ word: 'record', pos: 'v' }, { word: 'recording', pos: 'n' }] },
  { members: [{ word: 'recover', pos: 'v' }, { word: 'recovery', pos: 'n' }] },
  { members: [{ word: 'reduce', pos: 'v' }, { word: 'reduction', pos: 'n' }] },
  { members: [{ word: 'refer', pos: 'v' }, { word: 'reference', pos: 'n' }] },
  { members: [{ word: 'reflect', pos: 'v' }, { word: 'reflection', pos: 'n' }] },
  { members: [{ word: 'reform', pos: 'v' }, { word: 'reformation', pos: 'n' }] },
  { members: [{ word: 'refuse', pos: 'v' }, { word: 'refusal', pos: 'n' }] },
  { members: [{ word: 'regulate', pos: 'v' }, { word: 'regulation', pos: 'n' }] },
  { members: [{ word: 'relax', pos: 'v' }, { word: 'relaxation', pos: 'n' }] },
  { members: [{ word: 'rely', pos: 'v' }, { word: 'reliance', pos: 'n' }, { word: 'reliable', pos: 'adj' }] },
  { members: [{ word: 'reluctant', pos: 'adj' }, { word: 'reluctance', pos: 'n' }] },
  { members: [{ word: 'remain', pos: 'v' }, { word: 'remains', pos: 'n' }] },
  { members: [{ word: 'remember', pos: 'v' }, { word: 'memory', pos: 'n' }] },
  { members: [{ word: 'remove', pos: 'v' }, { word: 'removal', pos: 'n' }] },
  { members: [{ word: 'renew', pos: 'v' }, { word: 'renewable', pos: 'adj' }] },
  { members: [{ word: 'represent', pos: 'v' }, { word: 'representation', pos: 'n' }, { word: 'representative', pos: 'n' }] },
  { members: [{ word: 'require', pos: 'v' }, { word: 'requirement', pos: 'n' }] },
  { members: [{ word: 'resist', pos: 'v' }, { word: 'resistance', pos: 'n' }] },
  { members: [{ word: 'resolve', pos: 'v' }, { word: 'resolution', pos: 'n' }] },
  { members: [{ word: 'respond', pos: 'v' }, { word: 'response', pos: 'n' }, { word: 'responsible', pos: 'adj' }] },
  { members: [{ word: 'restore', pos: 'v' }, { word: 'restoration', pos: 'n' }] },
  { members: [{ word: 'restrict', pos: 'v' }, { word: 'restriction', pos: 'n' }] },
  { members: [{ word: 'retire', pos: 'v' }, { word: 'retirement', pos: 'n' }] },
  { members: [{ word: 'reveal', pos: 'v' }, { word: 'revelation', pos: 'n' }] },
  { members: [{ word: 'revise', pos: 'v' }, { word: 'revision', pos: 'n' }] },
  { members: [{ word: 'ridicule', pos: 'v' }, { word: 'ridiculous', pos: 'adj' }] },
  { members: [{ word: 'satisfy', pos: 'v' }, { word: 'satisfaction', pos: 'n' }, { word: 'satisfactory', pos: 'adj' }] },
  { members: [{ word: 'science', pos: 'n' }, { word: 'scientific', pos: 'adj' }, { word: 'scientist', pos: 'n' }] },
  { members: [{ word: 'secure', pos: 'adj' }, { word: 'security', pos: 'n' }] },
  { members: [{ word: 'select', pos: 'v' }, { word: 'selection', pos: 'n' }] },
  { members: [{ word: 'sense', pos: 'n' }, { word: 'sensitive', pos: 'adj' }] },
  { members: [{ word: 'separate', pos: 'v' }, { word: 'separation', pos: 'n' }] },
  { members: [{ word: 'significant', pos: 'adj' }, { word: 'significance', pos: 'n' }] },
  { members: [{ word: 'similar', pos: 'adj' }, { word: 'similarity', pos: 'n' }] },
  { members: [{ word: 'simple', pos: 'adj' }, { word: 'simplicity', pos: 'n' }, { word: 'simplify', pos: 'v' }] },
  { members: [{ word: 'sincere', pos: 'adj' }, { word: 'sincerity', pos: 'n' }] },
  { members: [{ word: 'solve', pos: 'v' }, { word: 'solution', pos: 'n' }] },
  { members: [{ word: 'special', pos: 'adj' }, { word: 'specialist', pos: 'n' }, { word: 'specialize', pos: 'v' }] },
  { members: [{ word: 'specify', pos: 'v' }, { word: 'specific', pos: 'adj' }, { word: 'specification', pos: 'n' }] },
  { members: [{ word: 'stable', pos: 'adj' }, { word: 'stability', pos: 'n' }] },
  { members: [{ word: 'statistics', pos: 'n' }, { word: 'statistical', pos: 'adj' }] },
  { members: [{ word: 'strengthen', pos: 'v' }, { word: 'strength', pos: 'n' }] },
  { members: [{ word: 'stress', pos: 'v' }, { word: 'stressful', pos: 'adj' }] },
  { members: [{ word: 'succeed', pos: 'v' }, { word: 'success', pos: 'n' }, { word: 'successful', pos: 'adj' }] },
  { members: [{ word: 'suffer', pos: 'v' }, { word: 'suffering', pos: 'n' }] },
  { members: [{ word: 'suggest', pos: 'v' }, { word: 'suggestion', pos: 'n' }] },
  { members: [{ word: 'summarize', pos: 'v' }, { word: 'summary', pos: 'n' }] },
  { members: [{ word: 'supervise', pos: 'v' }, { word: 'supervision', pos: 'n' }, { word: 'supervisor', pos: 'n' }] },
  { members: [{ word: 'survive', pos: 'v' }, { word: 'survival', pos: 'n' }] },
  { members: [{ word: 'suspect', pos: 'v' }, { word: 'suspicion', pos: 'n' }, { word: 'suspicious', pos: 'adj' }] },
  { members: [{ word: 'sympathy', pos: 'n' }, { word: 'sympathize', pos: 'v' }, { word: 'sympathetic', pos: 'adj' }] },
  { members: [{ word: 'system', pos: 'n' }, { word: 'systematic', pos: 'adj' }] },
  { members: [{ word: 'theory', pos: 'n' }, { word: 'theoretical', pos: 'adj' }] },
  { members: [{ word: 'thorough', pos: 'adj' }, { word: 'thoroughly', pos: 'adv' }] },
  { members: [{ word: 'threat', pos: 'n' }, { word: 'threaten', pos: 'v' }, { word: 'threatening', pos: 'adj' }] },
  { members: [{ word: 'tolerate', pos: 'v' }, { word: 'tolerance', pos: 'n' }] },
  { members: [{ word: 'tradition', pos: 'n' }, { word: 'traditional', pos: 'adj' }] },
  { members: [{ word: 'transform', pos: 'v' }, { word: 'transformation', pos: 'n' }] },
  { members: [{ word: 'transmit', pos: 'v' }, { word: 'transmission', pos: 'n' }] },
  { members: [{ word: 'treat', pos: 'v' }, { word: 'treatment', pos: 'n' }] },
  { members: [{ word: 'true', pos: 'adj' }, { word: 'truth', pos: 'n' }, { word: 'truly', pos: 'adv' }] },
  { members: [{ word: 'understand', pos: 'v' }, { word: 'understanding', pos: 'n' }] },
  { members: [{ word: 'unite', pos: 'v' }, { word: 'unity', pos: 'n' }] },
  { members: [{ word: 'use', pos: 'v' }, { word: 'useful', pos: 'adj' }, { word: 'useless', pos: 'adj' }] },
  { members: [{ word: 'vary', pos: 'v' }, { word: 'variety', pos: 'n' }, { word: 'various', pos: 'adj' }] },
  { members: [{ word: 'violate', pos: 'v' }, { word: 'violation', pos: 'n' }] },
  { members: [{ word: 'violent', pos: 'adj' }, { word: 'violence', pos: 'n' }] },
  { members: [{ word: 'visible', pos: 'adj' }, { word: 'visibility', pos: 'n' }] },
  { members: [{ word: 'weak', pos: 'adj' }, { word: 'weakness', pos: 'n' }] },
  { members: [{ word: 'wise', pos: 'adj' }, { word: 'wisdom', pos: 'n' }] },
  { members: [{ word: 'wonder', pos: 'v' }, { word: 'wonderful', pos: 'adj' }] },
  { members: [{ word: 'worry', pos: 'v' }, { word: 'worried', pos: 'adj' }] },
]

const formIndex = new Map<string, Family>()
const allMembers: FamilyMember[] = []
for (const f of FAMILIES) {
  for (const m of f.members) {
    formIndex.set(m.word.toLowerCase(), f)
    allMembers.push(m)
  }
}

export function familyOf(word: string): Family | undefined {
  return formIndex.get(word.trim().toLowerCase())
}

export function memberOf(word: string): FamilyMember | undefined {
  const w = word.trim().toLowerCase()
  for (const f of FAMILIES) {
    for (const m of f.members) {
      if (m.word.toLowerCase() === w) return m
    }
  }
  return undefined
}

export function eligibleWords<T extends { text: string }>(words: T[]): T[] {
  return words.filter((w) => {
    const fam = familyOf(w.text)
    return fam && fam.members.length >= 2
  })
}

export function randomDistractors(target: FamilyMember, count: number): string[] {
  const pool = allMembers.filter((m) => m.pos === target.pos && m.word.toLowerCase() !== target.word.toLowerCase())
  const shuffled = pool.sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count).map((m) => m.word)
}
